/**
 * Emits src/data/db-stats-generated.ts — a tiny literal module with the
 * aggregate stats that used to be computed by importing the full 10MB
 * programs.ts at module load.
 *
 * WHY: db-stats was imported by the homepage (client component) just to
 * render "9,298+ programs", which transitively compiled the entire
 * program database into a 9.3MB client chunk (923kB First-Load JS on
 * the homepage, and the whole proprietary dataset visible in devtools).
 *
 * Run: npx tsx scripts/generate-db-stats.ts
 * Wired into `prebuild` so every `npm run build` regenerates it; the
 * vitest data-invariant suite fails CI if the committed file drifts
 * from the live computation.
 */
import { writeFileSync } from "fs";
import path from "path";
import { PROGRAMS } from "../src/data/programs";

interface Row {
  university_name?: string;
  country?: string;
  field_of_study?: string;
  verified_at?: string | null;
}

const uniSet = new Set<string>();
const countrySet = new Set<string>();
const fieldSet = new Set<string>();
const verifiedUniSet = new Set<string>();
let verifiedProgramCount = 0;
let totalPrograms = 0;
let maxVerifiedAt = "";
const byCountry: Record<string, Set<string>> = {};
const programCountByCountry: Record<string, number> = {};

for (const raw of PROGRAMS as unknown[]) {
  const p = raw as Row | undefined;
  if (!p || !p.university_name) continue;
  totalPrograms += 1;
  uniSet.add(p.university_name);
  if (p.country) {
    countrySet.add(p.country);
    (byCountry[p.country] ??= new Set()).add(p.university_name);
    programCountByCountry[p.country] = (programCountByCountry[p.country] ?? 0) + 1;
  }
  if (p.field_of_study) fieldSet.add(p.field_of_study);
  if (p.verified_at) {
    verifiedProgramCount += 1;
    verifiedUniSet.add(p.university_name);
    if (p.verified_at > maxVerifiedAt) maxVerifiedAt = p.verified_at;
  }
}

const universitiesByCountry: Record<string, string[]> = {};
for (const [c, s] of Object.entries(byCountry)) universitiesByCountry[c] = [...s].sort();

// University typeahead options (name, country, best-known QS rank) —
// consumed by roi-data's CURATED_UNIVERSITIES so the ROI Calculator and
// Parent Decision Tool typeaheads no longer import the 10MB programs.ts.
interface UniOption { name: string; country: string; qs_ranking: number | null }
const uniOptions = new Map<string, UniOption>();
for (const raw of PROGRAMS as unknown[]) {
  const p = raw as (Row & { qs_ranking?: number | null }) | undefined;
  if (!p || !p.university_name || !p.country) continue;
  const existing = uniOptions.get(p.university_name);
  if (!existing) {
    uniOptions.set(p.university_name, {
      name: p.university_name,
      country: p.country,
      qs_ranking: p.qs_ranking ?? null,
    });
  } else if (!existing.qs_ranking && p.qs_ranking) {
    existing.qs_ranking = p.qs_ranking;
  }
}
const universityOptions = [...uniOptions.values()].sort((a, b) => {
  if (a.qs_ranking && b.qs_ranking) return a.qs_ranking - b.qs_ranking;
  if (a.qs_ranking) return -1;
  if (b.qs_ranking) return 1;
  return a.name.localeCompare(b.name);
});

const programsByCountry = Object.entries(programCountByCountry)
  .map(([country, count]) => ({ country, count }))
  .sort((a, b) => b.count - a.count);

const payload = {
  totalPrograms,
  totalVerifiedPrograms: verifiedProgramCount,
  totalUniversities: uniSet.size,
  totalVerifiedUniversities: verifiedUniSet.size,
  totalCountries: countrySet.size,
  totalFields: fieldSet.size,
  maxVerifiedAt,
  universitiesByCountry,
  programsByCountry,
  universityOptions,
};

const out = `// AUTO-GENERATED by scripts/generate-db-stats.ts — do not edit by hand.
// Regenerate after any programs.ts change: npx tsx scripts/generate-db-stats.ts
// The vitest data-invariant suite fails if this file drifts from the live data.

export const GENERATED_DB_STATS = ${JSON.stringify(payload, null, 2)} as const;
`;

const dest = path.join(__dirname, "..", "src", "data", "db-stats-generated.ts");
writeFileSync(dest, out);
console.log(
  `Wrote ${dest}: ${totalPrograms} programs / ${uniSet.size} unis / ${countrySet.size} countries / maxVerifiedAt ${maxVerifiedAt}`,
);
