"use client";

// Real downloadable PDF for the Sample Parent Decision Report (Tier-C #16).
// Generated by @react-pdf/renderer — proper selectable text, not a raster
// snapshot of the browser's print view. The HTML version (page.tsx) keeps
// its Save-as-PDF button as a fallback; the new "Download PDF" path here
// goes through pdf(<Doc/>).toBlob() so the user gets a stable, printable,
// searchable file regardless of browser print quirks.
//
// Visual baseline: clean black-on-white with subtle gray accents. The HTML
// version uses gradients + colored cards that don't translate cleanly to
// PDF without heavyweight image work; the PDF stays typographic.

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { SAMPLE, FACTORS, COSTS, ROI, RISKS, SOURCES, SOURCE_LAST_VERIFIED, type Tone } from "./data";

const COLORS: Record<Tone, { bg: string; text: string }> = {
  good:    { bg: "#ECFDF5", text: "#047857" },
  warn:    { bg: "#FFFBEB", text: "#92400E" },
  neutral: { bg: "#F9FAFB", text: "#374151" },
  verdict: { bg: "#EEF2FF", text: "#3730A3" },
};

const styles = StyleSheet.create({
  page:       { padding: 36, fontSize: 10, fontFamily: "Helvetica", color: "#111827", lineHeight: 1.45 },
  headerRow:  { flexDirection: "row", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: "#E5E7EB", paddingBottom: 14, marginBottom: 18 },
  brand:      { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#111827" },
  brandAccent:{ fontSize: 11, fontFamily: "Helvetica-Bold", color: "#6366F1" },
  eyebrow:    { fontSize: 8, fontFamily: "Helvetica-Bold", color: "#6D28D9", letterSpacing: 1.2, marginTop: 8, marginBottom: 6, textTransform: "uppercase" },
  h1:         { fontSize: 18, fontFamily: "Helvetica-Bold", color: "#111827", marginBottom: 4 },
  sub:        { fontSize: 9, color: "#6B7280" },
  metaRight:  { textAlign: "right" },
  metaLabel:  { fontSize: 7, color: "#9CA3AF", letterSpacing: 1.2, textTransform: "uppercase" },
  metaValue:  { fontSize: 10, fontFamily: "Helvetica-Bold", color: "#111827" },
  metaNote:   { fontSize: 7, color: "#9CA3AF", marginTop: 6 },
  sectionH:   { fontSize: 8, fontFamily: "Helvetica-Bold", color: "#6B7280", textTransform: "uppercase", letterSpacing: 1.2, marginTop: 12, marginBottom: 8 },
  verdictBox: { padding: 12, backgroundColor: "#EEF2FF", borderWidth: 1, borderColor: "#C7D2FE", borderRadius: 8, marginBottom: 4 },
  verdictTitle: { fontSize: 13, fontFamily: "Helvetica-Bold", color: "#111827", marginBottom: 4 },
  verdictBody:  { fontSize: 10, color: "#374151" },
  factorRow:  { flexDirection: "row", padding: 8, borderWidth: 1, borderRadius: 6, marginBottom: 4 },
  factorMain: { flex: 1 },
  factorTitleRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 2 },
  factorName: { fontSize: 10, fontFamily: "Helvetica-Bold", color: "#111827" },
  factorView: { fontSize: 10, fontFamily: "Helvetica-Bold" },
  factorNote: { fontSize: 9, color: "#374151" },
  costTable:  { borderTopWidth: 1, borderTopColor: "#E5E7EB" },
  costRow:    { flexDirection: "row", paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: "#F3F4F6" },
  costRowTotal: { backgroundColor: "#F9FAFB" },
  costLabel:  { flex: 2, fontSize: 10, color: "#374151" },
  costAmount: { flex: 1, fontSize: 10, color: "#111827", textAlign: "right" },
  costInr:    { flex: 1, fontSize: 10, color: "#6B7280", textAlign: "right" },
  bold:       { fontFamily: "Helvetica-Bold" },
  roiGrid:    { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -4 },
  roiCard:    { width: "50%", padding: 4 },
  roiCardInner: { borderWidth: 1, borderColor: "#E5E7EB", borderRadius: 6, padding: 10 },
  roiLabel:   { fontSize: 7, fontFamily: "Helvetica-Bold", color: "#6B7280", textTransform: "uppercase", letterSpacing: 1, marginBottom: 4 },
  roiValue:   { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#111827" },
  riskRow:    { padding: 8, borderWidth: 1, borderRadius: 6, marginBottom: 4 },
  riskText:   { fontSize: 9, color: "#374151" },
  sourceBox:  { padding: 10, backgroundColor: "#F9FAFB", borderWidth: 1, borderColor: "#E5E7EB", borderRadius: 6, marginTop: 6 },
  sourceLine: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 2 },
  sourceField: { fontSize: 9, color: "#374151" },
  sourceSrc:   { fontSize: 9, color: "#6B7280" },
  sourceFoot:  { fontSize: 8, color: "#9CA3AF", marginTop: 8 },
  footer:     { borderTopWidth: 1, borderTopColor: "#E5E7EB", marginTop: 18, paddingTop: 12 },
  footerBody: { fontSize: 8, color: "#6B7280", lineHeight: 1.5 },
  footerNote: { fontSize: 7, color: "#9CA3AF", marginTop: 8 },
});

export function SampleParentReportPdfDoc() {
  return (
    <Document title={`Sample Parent Decision Report — ${SAMPLE.program}`} author="EduvianAI">
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.headerRow}>
          <View>
            <View style={{ flexDirection: "row", alignItems: "baseline" }}>
              <Text style={styles.brand}>eduvian</Text>
              <Text style={styles.brandAccent}>AI</Text>
            </View>
            <Text style={styles.eyebrow}>Parent Decision Report</Text>
            <Text style={styles.h1}>{SAMPLE.program}</Text>
            <Text style={styles.sub}>{SAMPLE.university} · {SAMPLE.country} · {SAMPLE.intake}</Text>
          </View>
          <View style={styles.metaRight}>
            <Text style={styles.metaLabel}>For</Text>
            <Text style={styles.metaValue}>{SAMPLE.studentInitial}</Text>
            <Text style={styles.metaNote}>{SAMPLE.generatedOn}</Text>
          </View>
        </View>

        {/* Family verdict */}
        <View style={styles.verdictBox}>
          <Text style={styles.metaLabel}>Family verdict</Text>
          <Text style={styles.verdictTitle}>Worth considering — strong on cost, safety and outcomes.</Text>
          <Text style={styles.verdictBody}>
            This program fits the family budget, has clear post-study work pathways, and ranks well on safety. The main open item is visa readiness — the SOP needs strengthening before filing.
          </Text>
        </View>

        {/* Seven-factor breakdown */}
        <Text style={styles.sectionH}>Seven-factor breakdown</Text>
        {FACTORS.map((f) => {
          const c = COLORS[f.tone];
          return (
            <View key={f.factor} style={[styles.factorRow, { backgroundColor: c.bg, borderColor: c.bg }]} wrap={false}>
              <View style={styles.factorMain}>
                <View style={styles.factorTitleRow}>
                  <Text style={styles.factorName}>{f.factor}</Text>
                  <Text style={[styles.factorView, { color: c.text }]}>{f.view}</Text>
                </View>
                <Text style={styles.factorNote}>{f.note}</Text>
              </View>
            </View>
          );
        })}

        {/* Cost breakdown */}
        <Text style={styles.sectionH}>Cost breakdown</Text>
        <View style={styles.costTable}>
          {COSTS.map((c) => (
            <View key={c.label} style={[styles.costRow, c.total ? styles.costRowTotal : {}]}>
              <Text style={[styles.costLabel, c.total ? styles.bold : {}]}>{c.label}</Text>
              <Text style={[styles.costAmount, c.total ? styles.bold : {}]}>{c.amount}</Text>
              <Text style={[styles.costInr, c.total ? styles.bold : {}]}>{c.inr}</Text>
            </View>
          ))}
        </View>

        {/* ROI snapshot */}
        <Text style={styles.sectionH}>10-year ROI snapshot</Text>
        <View style={styles.roiGrid}>
          {[
            { label: "Expected starting salary", value: ROI.expected_starting_salary },
            { label: "5-year earnings",          value: ROI.five_year_earnings },
            { label: "Break-even year",          value: ROI.break_even_year },
            { label: "Net value vs no-study",    value: ROI.net_value_10yr },
          ].map((r) => (
            <View key={r.label} style={styles.roiCard}>
              <View style={styles.roiCardInner}>
                <Text style={styles.roiLabel}>{r.label}</Text>
                <Text style={styles.roiValue}>{r.value}</Text>
              </View>
            </View>
          ))}
        </View>

        {/* Open items / risk flags */}
        <Text style={styles.sectionH}>Open items &amp; risk flags</Text>
        {RISKS.map((r, i) => {
          const c = r.tone === "ok" ? COLORS.good : COLORS.warn;
          return (
            <View key={i} style={[styles.riskRow, { backgroundColor: c.bg, borderColor: c.bg }]} wrap={false}>
              <Text style={[styles.riskText, { color: c.text }]}>{r.text}</Text>
            </View>
          );
        })}

        {/* Source proof */}
        <Text style={styles.sectionH}>Source proof</Text>
        <View style={styles.sourceBox}>
          {SOURCES.map((s) => (
            <View key={s.field} style={styles.sourceLine}>
              <Text style={styles.sourceField}>{s.field}</Text>
              <Text style={styles.sourceSrc}>{s.source}</Text>
            </View>
          ))}
          <Text style={styles.sourceFoot}>Last verified {SOURCE_LAST_VERIFIED} · Illustrative — sample student, not a real case.</Text>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerBody}>
            <Text style={styles.bold}>Decision-support estimate.</Text> Generated from the student&apos;s profile + verified-at-source program data. Final fees, eligibility, scholarships and visa rules should always be confirmed directly with the university and the relevant consulate before committing. EduvianAI is not a financial, legal or immigration adviser.
          </Text>
          <Text style={styles.footerNote}>
            Sample report · Numbers and case study are illustrative. Generate yours at eduvianai.com/parent-decision.
          </Text>
        </View>
      </Page>
    </Document>
  );
}
