// AUTO-GENERATED by scripts/generate-db-stats.ts — do not edit by hand.
// Regenerate after any programs.ts change: npx tsx scripts/generate-db-stats.ts
// The vitest data-invariant suite fails if this file drifts from the live data.

export const GENERATED_DB_STATS = {
  "totalPrograms": 10728,
  "totalVerifiedPrograms": 10728,
  "totalUniversities": 623,
  "totalVerifiedUniversities": 623,
  "totalCountries": 12,
  "totalFields": 30,
  "maxVerifiedAt": "2026-07-12T17:45:56.017Z",
  "universitiesByCountry": {
    "USA": [
      "Adelphi University",
      "American University",
      "Arizona State University",
      "Auburn University",
      "Baylor University",
      "Binghamton University",
      "Boston College",
      "Boston University",
      "Bradley University",
      "Brandeis University",
      "Brigham Young University",
      "Brown University",
      "Bucknell University",
      "California Institute of Technology",
      "California Polytechnic State University",
      "California State Polytechnic University, Pomona",
      "California State University, East Bay",
      "California State University, Fresno",
      "California State University, Fullerton",
      "California State University, Long Beach",
      "California State University, Northridge",
      "California State University, Sacramento",
      "Carnegie Mellon University",
      "Case Western Reserve University",
      "Chapman University",
      "Clemson University",
      "Cleveland State University",
      "College of William & Mary",
      "Colorado School of Mines",
      "Colorado State University",
      "Columbia University",
      "Cornell University",
      "Dartmouth College",
      "DePaul University",
      "Drexel University",
      "Duke University",
      "Emory University",
      "Florida Atlantic University",
      "Florida Institute of Technology",
      "Florida International University",
      "Florida Polytechnic University",
      "Florida State University",
      "Fordham University",
      "George Mason University",
      "George Washington University",
      "Georgetown University",
      "Georgia Institute of Technology",
      "Harvard University",
      "Harvey Mudd College",
      "Hofstra University",
      "Howard University",
      "Illinois Institute of Technology",
      "Indiana University Bloomington",
      "Iowa State University",
      "James Madison University",
      "Johns Hopkins University",
      "Kansas State University",
      "Kent State University",
      "Lamar University",
      "Lawrence Technological University",
      "Lehigh University",
      "Lewis University",
      "Long Island University",
      "Louisiana State University",
      "Loyola Marymount University",
      "Loyola University Chicago",
      "Marquette University",
      "Massachusetts Institute of Technology",
      "Miami University",
      "Michigan State University",
      "Michigan Technological University",
      "Mississippi State University",
      "Missouri University of Science and Technology",
      "NYU Stern School of Business",
      "New Jersey Institute of Technology",
      "New Mexico State University",
      "New York Institute of Technology",
      "New York University",
      "North Carolina State University",
      "Northeastern University",
      "Northern Arizona University",
      "Northern Illinois University",
      "Northwestern University",
      "Ohio State University",
      "Oklahoma State University",
      "Oregon State University",
      "Pace University",
      "Penn State University",
      "Pennsylvania State University",
      "Pepperdine University",
      "Pomona College",
      "Pratt Institute",
      "Princeton University",
      "Purdue University",
      "Quinnipiac University",
      "Rensselaer Polytechnic Institute",
      "Rhode Island School of Design",
      "Rice University",
      "Rochester Institute of Technology",
      "Rutgers University",
      "Rutgers University–New Brunswick",
      "Saint Louis University",
      "Saint Peter's University",
      "Sam Houston State University",
      "San Diego State University",
      "San Francisco State University",
      "San Jose State University",
      "Santa Clara University",
      "Savannah College of Art and Design",
      "Southern Illinois University Edwardsville",
      "Southern Methodist University",
      "Stanford University",
      "Stevens Institute of Technology",
      "Stony Brook University",
      "Syracuse University",
      "Temple University",
      "Texas A&M University",
      "Texas State University",
      "Texas Tech University",
      "Texas Woman's University",
      "The New School",
      "Tufts University",
      "Tulane University",
      "UC Riverside",
      "UC Santa Cruz",
      "UCLA",
      "University at Albany, SUNY",
      "University at Buffalo (SUNY)",
      "University at Buffalo, SUNY",
      "University of Akron",
      "University of Alabama",
      "University of Arizona",
      "University of Arkansas",
      "University of Bridgeport",
      "University of California, Berkeley",
      "University of California, Davis",
      "University of California, Irvine",
      "University of California, Los Angeles",
      "University of California, San Diego",
      "University of California, Santa Barbara",
      "University of Central Florida",
      "University of Chicago",
      "University of Cincinnati",
      "University of Colorado Boulder",
      "University of Connecticut",
      "University of Dayton",
      "University of Delaware",
      "University of Detroit Mercy",
      "University of Florida",
      "University of Georgia",
      "University of Hartford",
      "University of Hawaii at Manoa",
      "University of Houston",
      "University of Houston-Clear Lake",
      "University of Illinois at Chicago",
      "University of Illinois at Urbana-Champaign",
      "University of Iowa",
      "University of Kansas",
      "University of Kentucky",
      "University of Louisville",
      "University of Maryland",
      "University of Maryland, Baltimore County",
      "University of Massachusetts Amherst",
      "University of Massachusetts Boston",
      "University of Massachusetts Lowell",
      "University of Memphis",
      "University of Miami",
      "University of Michigan",
      "University of Minnesota",
      "University of Mississippi",
      "University of Missouri",
      "University of Nebraska-Lincoln",
      "University of New Hampshire",
      "University of New Haven",
      "University of New Mexico",
      "University of North Carolina at Chapel Hill",
      "University of North Carolina at Charlotte",
      "University of North Dakota",
      "University of North Texas",
      "University of Notre Dame",
      "University of Oklahoma",
      "University of Oregon",
      "University of Pennsylvania",
      "University of Pittsburgh",
      "University of Rochester",
      "University of San Diego",
      "University of San Francisco",
      "University of South Carolina",
      "University of South Dakota",
      "University of South Florida",
      "University of Southern California",
      "University of Tennessee",
      "University of Tennessee Knoxville",
      "University of Texas Rio Grande Valley",
      "University of Texas at Arlington",
      "University of Texas at Austin",
      "University of Texas at Dallas",
      "University of Texas at San Antonio",
      "University of Toledo",
      "University of Tulsa",
      "University of Utah",
      "University of Vermont",
      "University of Virginia",
      "University of Washington",
      "University of Wisconsin-Madison",
      "University of Wisconsin-Milwaukee",
      "Vanderbilt University",
      "Virginia Tech",
      "Wake Forest University",
      "Washington State University",
      "Washington University in St. Louis",
      "Wayne State University",
      "West Virginia University",
      "Western Illinois University",
      "Wichita State University",
      "Worcester Polytechnic Institute",
      "Wright State University",
      "Yale University",
      "Yeshiva University"
    ],
    "UK": [
      "Abertay University",
      "Aberystwyth University",
      "Anglia Ruskin University",
      "Arts University Bournemouth",
      "Aston University",
      "BPP University",
      "Bangor University",
      "Bath Spa University",
      "Birkbeck, University of London",
      "Birmingham City University",
      "Bournemouth University",
      "Brunel University London",
      "Canterbury Christ Church University",
      "Cardiff Metropolitan University",
      "Cardiff University",
      "City, University of London",
      "Coventry University",
      "De Montfort University",
      "Durham University",
      "Edge Hill University",
      "Edinburgh Napier University",
      "Falmouth University",
      "Glasgow Caledonian University",
      "Goldsmiths, University of London",
      "Harper Adams University",
      "Heriot-Watt University",
      "Imperial College London",
      "Keele University",
      "King's College London",
      "Kingston University London",
      "Lancaster University",
      "Leeds Beckett University",
      "Leeds Trinity University",
      "Liverpool Hope University",
      "Liverpool John Moores University",
      "London Metropolitan University",
      "London School of Economics",
      "London South Bank University",
      "Loughborough University",
      "Manchester Metropolitan University",
      "Middlesex University",
      "Middlesex University London",
      "Newcastle University",
      "Oxford Brookes University",
      "Queen Margaret University",
      "Queen Mary University of London",
      "Queen's University Belfast",
      "Regent's University London",
      "Robert Gordon University",
      "Royal Agricultural University",
      "Royal College of Art",
      "Royal Holloway, University of London",
      "Royal Veterinary College",
      "SOAS, University of London",
      "Sheffield Hallam University",
      "Solent University",
      "St George's, University of London",
      "St Mary's University, Twickenham",
      "Staffordshire University",
      "Swansea University",
      "Teesside University",
      "UCL",
      "Ulster University",
      "University College London",
      "University of Aberdeen",
      "University of Bath",
      "University of Birmingham",
      "University of Bradford",
      "University of Brighton",
      "University of Bristol",
      "University of Buckingham",
      "University of Cambridge",
      "University of Central Lancashire",
      "University of Chester",
      "University of Cumbria",
      "University of Derby",
      "University of Dundee",
      "University of East Anglia",
      "University of East London",
      "University of Edinburgh",
      "University of Essex",
      "University of Exeter",
      "University of Glasgow",
      "University of Gloucestershire",
      "University of Greenwich",
      "University of Hertfordshire",
      "University of Highlands and Islands",
      "University of Huddersfield",
      "University of Hull",
      "University of Kent",
      "University of Law",
      "University of Leeds",
      "University of Leicester",
      "University of Lincoln",
      "University of Liverpool",
      "University of Manchester",
      "University of Northampton",
      "University of Nottingham",
      "University of Oxford",
      "University of Plymouth",
      "University of Portsmouth",
      "University of Reading",
      "University of Roehampton",
      "University of Salford",
      "University of Sheffield",
      "University of South Wales",
      "University of Southampton",
      "University of St Andrews",
      "University of Stirling",
      "University of Strathclyde",
      "University of Suffolk",
      "University of Sunderland",
      "University of Surrey",
      "University of Sussex",
      "University of Warwick",
      "University of West London",
      "University of Westminster",
      "University of Winchester",
      "University of Wolverhampton",
      "University of Worcester",
      "University of York",
      "University of the Arts London",
      "University of the West of England",
      "University of the West of Scotland",
      "York St John University"
    ],
    "Australia": [
      "Australian Catholic University",
      "Australian National University",
      "Bond University",
      "CQUniversity Australia",
      "Charles Darwin University",
      "Charles Sturt University",
      "Curtin University",
      "Deakin University",
      "Edith Cowan University",
      "Federation University Australia",
      "Flinders University",
      "Griffith University",
      "Holmes Institute",
      "James Cook University",
      "La Trobe University",
      "Macquarie University",
      "Monash University",
      "Murdoch University",
      "Queensland University of Technology",
      "RMIT University",
      "Southern Cross University",
      "Swinburne University of Technology",
      "Torrens University Australia",
      "UNSW Sydney",
      "University of Adelaide",
      "University of Adelaide College",
      "University of Canberra",
      "University of Divinity",
      "University of Melbourne",
      "University of New England",
      "University of New South Wales",
      "University of Newcastle",
      "University of Queensland",
      "University of Southern Queensland",
      "University of Sydney",
      "University of Tasmania",
      "University of Technology Sydney",
      "University of Western Australia",
      "University of Wollongong",
      "University of the Sunshine Coast",
      "Victoria University",
      "Western Sydney University"
    ],
    "Canada": [
      "Acadia University",
      "Algoma University",
      "Algonquin College",
      "Athabasca University",
      "Bishop's University",
      "British Columbia Institute of Technology (BCIT)",
      "Brock University",
      "Camosun College",
      "Cape Breton University",
      "Capilano University",
      "Carleton University",
      "Centennial College",
      "Concordia University",
      "Conestoga College",
      "Dalhousie University",
      "Durham College",
      "Fanshawe College",
      "Georgian College",
      "Holland College",
      "Humber Polytechnic",
      "Kwantlen Polytechnic University",
      "Lakehead University",
      "Langara College",
      "Laurentian University",
      "MacEwan University",
      "McGill University",
      "McMaster University",
      "Memorial University of Newfoundland",
      "Mohawk College",
      "Mount Allison University",
      "Mount Royal University",
      "Niagara College",
      "OCAD University",
      "Queen's University",
      "Royal Roads University",
      "Saint Mary's University",
      "Selkirk College",
      "Seneca Polytechnic",
      "Sheridan College",
      "Simon Fraser University",
      "Southern Alberta Institute of Technology (SAIT)",
      "St. Francis Xavier University",
      "Thompson Rivers University",
      "Toronto Metropolitan University",
      "Trent University",
      "Trinity Western University",
      "University of Alberta",
      "University of British Columbia",
      "University of Calgary",
      "University of Guelph",
      "University of Lethbridge",
      "University of Manitoba",
      "University of Montreal",
      "University of New Brunswick",
      "University of Northern British Columbia",
      "University of Ottawa",
      "University of Regina",
      "University of Saskatchewan",
      "University of Toronto",
      "University of Victoria",
      "University of Waterloo",
      "University of Windsor",
      "University of Winnipeg",
      "University of the Fraser Valley",
      "Université Laval",
      "Université du Québec à Montréal",
      "Vancouver Island University",
      "Western University",
      "Wilfrid Laurier University",
      "York University"
    ],
    "New Zealand": [
      "Auckland University of Technology",
      "Lincoln University NZ",
      "Massey University",
      "University of Auckland",
      "University of Canterbury",
      "University of Otago",
      "University of Waikato",
      "Victoria University of Wellington"
    ],
    "Ireland": [
      "Atlantic Technological University",
      "Maynooth University",
      "Munster Technological University",
      "National University of Ireland Galway",
      "Royal College of Surgeons in Ireland",
      "Technological University Dublin",
      "Trinity College Dublin",
      "University College Cork",
      "University College Dublin",
      "University of Galway"
    ],
    "Germany": [
      "Charité – Universitätsmedizin Berlin",
      "ESMT Berlin",
      "FH Aachen",
      "Frankfurt School of Finance & Management",
      "Free University of Berlin",
      "Friedrich Schiller University Jena",
      "Friedrich-Alexander University Erlangen-Nürnberg",
      "GISMA University of Applied Sciences",
      "Goethe University Frankfurt",
      "HAW Hamburg",
      "HHL Leipzig Graduate School of Management",
      "HTW Berlin",
      "Hamburg University of Technology",
      "Heidelberg University",
      "Heinrich Heine University Düsseldorf",
      "Hochschule Düsseldorf",
      "Hochschule München",
      "Humboldt University Berlin",
      "Johannes Gutenberg University Mainz",
      "Justus Liebig University Giessen",
      "Karlsruhe Institute of Technology",
      "Kiel University",
      "Leibniz University Hannover",
      "Leipzig University",
      "Martin Luther University Halle-Wittenberg",
      "Munich Business School",
      "Philipps University of Marburg",
      "RWTH Aachen University",
      "Ruhr University Bochum",
      "Saarland University",
      "TU Darmstadt",
      "TU Dresden",
      "Technical University of Berlin",
      "Technical University of Darmstadt",
      "Technical University of Munich",
      "Ulm University",
      "University of Augsburg",
      "University of Bayreuth",
      "University of Bonn",
      "University of Bremen",
      "University of Cologne",
      "University of Freiburg",
      "University of Greifswald",
      "University of Hamburg",
      "University of Konstanz",
      "University of Mannheim",
      "University of Munich (LMU)",
      "University of Münster",
      "University of Potsdam",
      "University of Rostock",
      "University of Stuttgart",
      "University of Tübingen",
      "University of Würzburg",
      "WHU – Otto Beisheim School of Management"
    ],
    "France": [
      "Aix-Marseille University",
      "Audencia Business School",
      "Burgundy School of Business",
      "Centrale Lille",
      "Centrale Nantes",
      "CentraleSupélec",
      "EDHEC Business School",
      "EM Lyon Business School",
      "EPF Engineering School",
      "ESCE International Business School",
      "ESCP Business School",
      "ESSEC Business School",
      "Grenoble Ecole de Management",
      "HEC Paris",
      "IMT Atlantique",
      "INSEAD",
      "IÉSEG School of Management",
      "KEDGE Business School",
      "Mines ParisTech (PSL)",
      "PSL Research University",
      "Rennes School of Business",
      "SKEMA Business School",
      "Sciences Po",
      "Sorbonne University",
      "Sorbonne Université",
      "Toulouse School of Economics",
      "University of Bordeaux",
      "University of Montpellier",
      "University of Nantes",
      "University of Strasbourg",
      "Université Grenoble Alpes",
      "Université Paris Cité",
      "Université Paris-Saclay",
      "Université Toulouse III",
      "Université de Lyon",
      "École Normale Supérieure",
      "École Normale Supérieure (ENS)",
      "École Polytechnique"
    ],
    "UAE": [
      "Abu Dhabi University",
      "American University in Dubai",
      "American University of Sharjah",
      "BITS Pilani Dubai Campus",
      "Canadian University Dubai",
      "Curtin University Dubai",
      "Heriot-Watt University Dubai",
      "Higher Colleges of Technology",
      "Khalifa University",
      "Manipal Academy of Higher Education Dubai",
      "Middlesex University Dubai",
      "Mohamed bin Zayed University of Artificial Intelligence",
      "Murdoch University Dubai",
      "New York University Abu Dhabi",
      "RIT Dubai",
      "United Arab Emirates University",
      "University of Sharjah",
      "Zayed University"
    ],
    "Singapore": [
      "Curtin University Singapore",
      "ESSEC Asia-Pacific Singapore",
      "INSEAD Asia Campus",
      "James Cook University Singapore",
      "Nanyang Technological University",
      "National University of Singapore",
      "S P Jain School of Global Management Singapore",
      "Singapore Institute of Technology",
      "Singapore Management University",
      "Singapore University of Technology and Design"
    ],
    "Malaysia": [
      "Asia Pacific University of Technology & Innovation",
      "Curtin University Malaysia",
      "HELP University",
      "Heriot-Watt University Malaysia",
      "INTI International University",
      "International Islamic University Malaysia",
      "Multimedia University",
      "SEGi University",
      "Sunway University",
      "Swinburne University of Technology Sarawak",
      "Taylor's University",
      "UCSI University",
      "Universiti Kebangsaan Malaysia",
      "Universiti Malaya",
      "Universiti Putra Malaysia",
      "Universiti Sains Malaysia",
      "Universiti Teknologi Malaysia",
      "Universiti Tunku Abdul Rahman",
      "University of Nottingham Malaysia"
    ],
    "Netherlands": [
      "Delft University of Technology",
      "Eindhoven University of Technology",
      "Erasmus University Rotterdam",
      "Leiden University",
      "Maastricht University",
      "University of Amsterdam",
      "University of Groningen",
      "University of Twente",
      "Vrije Universiteit Amsterdam",
      "Wageningen University & Research"
    ]
  },
  "programsByCountry": [
    {
      "country": "USA",
      "count": 3979
    },
    {
      "country": "UK",
      "count": 2558
    },
    {
      "country": "Canada",
      "count": 1010
    },
    {
      "country": "Germany",
      "count": 825
    },
    {
      "country": "Australia",
      "count": 752
    },
    {
      "country": "France",
      "count": 454
    },
    {
      "country": "Malaysia",
      "count": 268
    },
    {
      "country": "UAE",
      "count": 219
    },
    {
      "country": "Netherlands",
      "count": 207
    },
    {
      "country": "New Zealand",
      "count": 178
    },
    {
      "country": "Ireland",
      "count": 167
    },
    {
      "country": "Singapore",
      "count": 111
    }
  ],
  "universityOptions": [
    {
      "name": "Massachusetts Institute of Technology",
      "country": "USA",
      "qs_ranking": 1
    },
    {
      "name": "University of Cambridge",
      "country": "UK",
      "qs_ranking": 2
    },
    {
      "name": "Harvard University",
      "country": "USA",
      "qs_ranking": 4
    },
    {
      "name": "University of Oxford",
      "country": "UK",
      "qs_ranking": 4
    },
    {
      "name": "Stanford University",
      "country": "USA",
      "qs_ranking": 5
    },
    {
      "name": "California Institute of Technology",
      "country": "USA",
      "qs_ranking": 6
    },
    {
      "name": "Imperial College London",
      "country": "UK",
      "qs_ranking": 6
    },
    {
      "name": "National University of Singapore",
      "country": "Singapore",
      "qs_ranking": 8
    },
    {
      "name": "University College London",
      "country": "UK",
      "qs_ranking": 9
    },
    {
      "name": "UCL",
      "country": "UK",
      "qs_ranking": 9
    },
    {
      "name": "University of California, Berkeley",
      "country": "USA",
      "qs_ranking": 10
    },
    {
      "name": "INSEAD",
      "country": "France",
      "qs_ranking": 11
    },
    {
      "name": "INSEAD Asia Campus",
      "country": "Singapore",
      "qs_ranking": 11
    },
    {
      "name": "University of Pennsylvania",
      "country": "USA",
      "qs_ranking": 12
    },
    {
      "name": "University of Melbourne",
      "country": "Australia",
      "qs_ranking": 13
    },
    {
      "name": "Cornell University",
      "country": "USA",
      "qs_ranking": 13
    },
    {
      "name": "Nanyang Technological University",
      "country": "Singapore",
      "qs_ranking": 15
    },
    {
      "name": "Yale University",
      "country": "USA",
      "qs_ranking": 16
    },
    {
      "name": "University of Michigan",
      "country": "USA",
      "qs_ranking": 17
    },
    {
      "name": "University of Sydney",
      "country": "Australia",
      "qs_ranking": 18
    },
    {
      "name": "University of New South Wales",
      "country": "Australia",
      "qs_ranking": 19
    },
    {
      "name": "UNSW Sydney",
      "country": "Australia",
      "qs_ranking": 19
    },
    {
      "name": "Columbia University",
      "country": "USA",
      "qs_ranking": 20
    },
    {
      "name": "University of Chicago",
      "country": "USA",
      "qs_ranking": 21
    },
    {
      "name": "Princeton University",
      "country": "USA",
      "qs_ranking": 22
    },
    {
      "name": "Johns Hopkins University",
      "country": "USA",
      "qs_ranking": 23
    },
    {
      "name": "PSL Research University",
      "country": "France",
      "qs_ranking": 24
    },
    {
      "name": "University of Toronto",
      "country": "Canada",
      "qs_ranking": 25
    },
    {
      "name": "École Normale Supérieure (ENS)",
      "country": "France",
      "qs_ranking": 26
    },
    {
      "name": "University of Edinburgh",
      "country": "UK",
      "qs_ranking": 27
    },
    {
      "name": "Australian National University",
      "country": "Australia",
      "qs_ranking": 30
    },
    {
      "name": "McGill University",
      "country": "Canada",
      "qs_ranking": 31
    },
    {
      "name": "Northwestern University",
      "country": "USA",
      "qs_ranking": 33
    },
    {
      "name": "University of Manchester",
      "country": "UK",
      "qs_ranking": 34
    },
    {
      "name": "Monash University",
      "country": "Australia",
      "qs_ranking": 36
    },
    {
      "name": "Technical University of Munich",
      "country": "Germany",
      "qs_ranking": 37
    },
    {
      "name": "New York University",
      "country": "USA",
      "qs_ranking": 39
    },
    {
      "name": "NYU Stern School of Business",
      "country": "USA",
      "qs_ranking": 40
    },
    {
      "name": "King's College London",
      "country": "UK",
      "qs_ranking": 40
    },
    {
      "name": "Sorbonne University",
      "country": "France",
      "qs_ranking": 41
    },
    {
      "name": "École Polytechnique",
      "country": "France",
      "qs_ranking": 42
    },
    {
      "name": "University of California, Los Angeles",
      "country": "USA",
      "qs_ranking": 42
    },
    {
      "name": "University of Queensland",
      "country": "Australia",
      "qs_ranking": 43
    },
    {
      "name": "UCLA",
      "country": "USA",
      "qs_ranking": 44
    },
    {
      "name": "University of British Columbia",
      "country": "Canada",
      "qs_ranking": 46
    },
    {
      "name": "London School of Economics",
      "country": "UK",
      "qs_ranking": 50
    },
    {
      "name": "École Normale Supérieure",
      "country": "France",
      "qs_ranking": 50
    },
    {
      "name": "Duke University",
      "country": "USA",
      "qs_ranking": 51
    },
    {
      "name": "Carnegie Mellon University",
      "country": "USA",
      "qs_ranking": 52
    },
    {
      "name": "University of Munich (LMU)",
      "country": "Germany",
      "qs_ranking": 54
    },
    {
      "name": "University of Bristol",
      "country": "UK",
      "qs_ranking": 55
    },
    {
      "name": "University of Amsterdam",
      "country": "Netherlands",
      "qs_ranking": 55
    },
    {
      "name": "Delft University of Technology",
      "country": "Netherlands",
      "qs_ranking": 56
    },
    {
      "name": "Mines ParisTech (PSL)",
      "country": "France",
      "qs_ranking": 56
    },
    {
      "name": "Sorbonne Université",
      "country": "France",
      "qs_ranking": 59
    },
    {
      "name": "University of Washington",
      "country": "USA",
      "qs_ranking": 61
    },
    {
      "name": "Universiti Malaya",
      "country": "Malaysia",
      "qs_ranking": 65
    },
    {
      "name": "University of Illinois at Urbana-Champaign",
      "country": "USA",
      "qs_ranking": 65
    },
    {
      "name": "University of California, San Diego",
      "country": "USA",
      "qs_ranking": 67
    },
    {
      "name": "University of Auckland",
      "country": "New Zealand",
      "qs_ranking": 68
    },
    {
      "name": "University of Warwick",
      "country": "UK",
      "qs_ranking": 69
    },
    {
      "name": "University of Texas at Austin",
      "country": "USA",
      "qs_ranking": 71
    },
    {
      "name": "Université Paris-Saclay",
      "country": "France",
      "qs_ranking": 71
    },
    {
      "name": "University of Leeds",
      "country": "UK",
      "qs_ranking": 75
    },
    {
      "name": "University of Glasgow",
      "country": "UK",
      "qs_ranking": 77
    },
    {
      "name": "University of Western Australia",
      "country": "Australia",
      "qs_ranking": 77
    },
    {
      "name": "Brown University",
      "country": "USA",
      "qs_ranking": 79
    },
    {
      "name": "University of Birmingham",
      "country": "UK",
      "qs_ranking": 79
    },
    {
      "name": "University of Southampton",
      "country": "UK",
      "qs_ranking": 81
    },
    {
      "name": "Trinity College Dublin",
      "country": "Ireland",
      "qs_ranking": 81
    },
    {
      "name": "Pennsylvania State University",
      "country": "USA",
      "qs_ranking": 81
    },
    {
      "name": "University of Adelaide",
      "country": "Australia",
      "qs_ranking": 82
    },
    {
      "name": "Heidelberg University",
      "country": "Germany",
      "qs_ranking": 84
    },
    {
      "name": "University of Wisconsin-Madison",
      "country": "USA",
      "qs_ranking": 87
    },
    {
      "name": "Durham University",
      "country": "UK",
      "qs_ranking": 92
    },
    {
      "name": "University of St Andrews",
      "country": "UK",
      "qs_ranking": 95
    },
    {
      "name": "University of North Carolina at Chapel Hill",
      "country": "USA",
      "qs_ranking": 95
    },
    {
      "name": "Georgia Institute of Technology",
      "country": "USA",
      "qs_ranking": 97
    },
    {
      "name": "Free University of Berlin",
      "country": "Germany",
      "qs_ranking": 97
    },
    {
      "name": "RWTH Aachen University",
      "country": "Germany",
      "qs_ranking": 99
    },
    {
      "name": "University of Sheffield",
      "country": "UK",
      "qs_ranking": 105
    },
    {
      "name": "University of Nottingham",
      "country": "UK",
      "qs_ranking": 108
    },
    {
      "name": "University of Nottingham Malaysia",
      "country": "Malaysia",
      "qs_ranking": 108
    },
    {
      "name": "Purdue University",
      "country": "USA",
      "qs_ranking": 109
    },
    {
      "name": "Newcastle University",
      "country": "UK",
      "qs_ranking": 110
    },
    {
      "name": "University of Alberta",
      "country": "Canada",
      "qs_ranking": 111
    },
    {
      "name": "University of Waterloo",
      "country": "Canada",
      "qs_ranking": 112
    },
    {
      "name": "Boston University",
      "country": "USA",
      "qs_ranking": 112
    },
    {
      "name": "University of Montreal",
      "country": "Canada",
      "qs_ranking": 116
    },
    {
      "name": "Leiden University",
      "country": "Netherlands",
      "qs_ranking": 119
    },
    {
      "name": "Eindhoven University of Technology",
      "country": "Netherlands",
      "qs_ranking": 119
    },
    {
      "name": "Karlsruhe Institute of Technology",
      "country": "Germany",
      "qs_ranking": 119
    },
    {
      "name": "Penn State University",
      "country": "USA",
      "qs_ranking": 123
    },
    {
      "name": "University of California, Davis",
      "country": "USA",
      "qs_ranking": 123
    },
    {
      "name": "Humboldt University Berlin",
      "country": "Germany",
      "qs_ranking": 130
    },
    {
      "name": "Wageningen University & Research",
      "country": "Netherlands",
      "qs_ranking": 130
    },
    {
      "name": "Queen Mary University of London",
      "country": "UK",
      "qs_ranking": 130
    },
    {
      "name": "Michigan State University",
      "country": "USA",
      "qs_ranking": 130
    },
    {
      "name": "University of Southern California",
      "country": "USA",
      "qs_ranking": 137
    },
    {
      "name": "Universiti Kebangsaan Malaysia",
      "country": "Malaysia",
      "qs_ranking": 138
    },
    {
      "name": "University of Maryland",
      "country": "USA",
      "qs_ranking": 138
    },
    {
      "name": "University of Groningen",
      "country": "Netherlands",
      "qs_ranking": 139
    },
    {
      "name": "Lancaster University",
      "country": "UK",
      "qs_ranking": 140
    },
    {
      "name": "University of Minnesota",
      "country": "USA",
      "qs_ranking": 144
    },
    {
      "name": "Universiti Sains Malaysia",
      "country": "Malaysia",
      "qs_ranking": 146
    },
    {
      "name": "University of Technology Sydney",
      "country": "Australia",
      "qs_ranking": 148
    },
    {
      "name": "Ohio State University",
      "country": "USA",
      "qs_ranking": 148
    },
    {
      "name": "Texas A&M University",
      "country": "USA",
      "qs_ranking": 148
    },
    {
      "name": "Universiti Putra Malaysia",
      "country": "Malaysia",
      "qs_ranking": 148
    },
    {
      "name": "University of Exeter",
      "country": "UK",
      "qs_ranking": 149
    },
    {
      "name": "University of Bath",
      "country": "UK",
      "qs_ranking": 150
    },
    {
      "name": "University of Calgary",
      "country": "Canada",
      "qs_ranking": 154
    },
    {
      "name": "University of California, Santa Barbara",
      "country": "USA",
      "qs_ranking": 157
    },
    {
      "name": "Emory University",
      "country": "USA",
      "qs_ranking": 159
    },
    {
      "name": "University of Florida",
      "country": "USA",
      "qs_ranking": 162
    },
    {
      "name": "Rice University",
      "country": "USA",
      "qs_ranking": 164
    },
    {
      "name": "University of Liverpool",
      "country": "UK",
      "qs_ranking": 165
    },
    {
      "name": "University of York",
      "country": "UK",
      "qs_ranking": 168
    },
    {
      "name": "University College Dublin",
      "country": "Ireland",
      "qs_ranking": 171
    },
    {
      "name": "Vanderbilt University",
      "country": "USA",
      "qs_ranking": 174
    },
    {
      "name": "Curtin University Dubai",
      "country": "UAE",
      "qs_ranking": 174
    },
    {
      "name": "Technical University of Berlin",
      "country": "Germany",
      "qs_ranking": 174
    },
    {
      "name": "Curtin University Malaysia",
      "country": "Malaysia",
      "qs_ranking": 174
    },
    {
      "name": "Curtin University Singapore",
      "country": "Singapore",
      "qs_ranking": 174
    },
    {
      "name": "Washington University in St. Louis",
      "country": "USA",
      "qs_ranking": 176
    },
    {
      "name": "Khalifa University",
      "country": "UAE",
      "qs_ranking": 181
    },
    {
      "name": "Universiti Teknologi Malaysia",
      "country": "Malaysia",
      "qs_ranking": 181
    },
    {
      "name": "University of Otago",
      "country": "New Zealand",
      "qs_ranking": 184
    },
    {
      "name": "RMIT University",
      "country": "Australia",
      "qs_ranking": 188
    },
    {
      "name": "McMaster University",
      "country": "Canada",
      "qs_ranking": 189
    },
    {
      "name": "University of Hamburg",
      "country": "Germany",
      "qs_ranking": 191
    },
    {
      "name": "University of Ottawa",
      "country": "Canada",
      "qs_ranking": 191
    },
    {
      "name": "Maastricht University",
      "country": "Netherlands",
      "qs_ranking": 192
    },
    {
      "name": "Macquarie University",
      "country": "Australia",
      "qs_ranking": 195
    },
    {
      "name": "University of Wollongong",
      "country": "Australia",
      "qs_ranking": 196
    },
    {
      "name": "University of Pittsburgh",
      "country": "USA",
      "qs_ranking": 196
    },
    {
      "name": "University of Newcastle",
      "country": "Australia",
      "qs_ranking": 197
    },
    {
      "name": "Cardiff University",
      "country": "UK",
      "qs_ranking": 197
    },
    {
      "name": "Queen's University Belfast",
      "country": "UK",
      "qs_ranking": 197
    },
    {
      "name": "Erasmus University Rotterdam",
      "country": "Netherlands",
      "qs_ranking": 199
    },
    {
      "name": "University of Twente",
      "country": "Netherlands",
      "qs_ranking": 199
    },
    {
      "name": "University of Tübingen",
      "country": "Germany",
      "qs_ranking": 206
    },
    {
      "name": "Northeastern University",
      "country": "USA",
      "qs_ranking": 210
    },
    {
      "name": "Queen's University",
      "country": "Canada",
      "qs_ranking": 213
    },
    {
      "name": "University of Freiburg",
      "country": "Germany",
      "qs_ranking": 213
    },
    {
      "name": "Arizona State University",
      "country": "USA",
      "qs_ranking": 216
    },
    {
      "name": "Vrije Universiteit Amsterdam",
      "country": "Netherlands",
      "qs_ranking": 219
    },
    {
      "name": "Technical University of Darmstadt",
      "country": "Germany",
      "qs_ranking": 224
    },
    {
      "name": "University of California, Irvine",
      "country": "USA",
      "qs_ranking": 226
    },
    {
      "name": "Georgetown University",
      "country": "USA",
      "qs_ranking": 228
    },
    {
      "name": "La Trobe University",
      "country": "Australia",
      "qs_ranking": 230
    },
    {
      "name": "Rutgers University",
      "country": "USA",
      "qs_ranking": 231
    },
    {
      "name": "Curtin University",
      "country": "Australia",
      "qs_ranking": 232
    },
    {
      "name": "University of Bonn",
      "country": "Germany",
      "qs_ranking": 232
    },
    {
      "name": "CentraleSupélec",
      "country": "France",
      "qs_ranking": 234
    },
    {
      "name": "Loughborough University",
      "country": "UK",
      "qs_ranking": 234
    },
    {
      "name": "University of Rochester",
      "country": "USA",
      "qs_ranking": 236
    },
    {
      "name": "Massey University",
      "country": "New Zealand",
      "qs_ranking": 239
    },
    {
      "name": "Victoria University of Wellington",
      "country": "New Zealand",
      "qs_ranking": 240
    },
    {
      "name": "Dartmouth College",
      "country": "USA",
      "qs_ranking": 243
    },
    {
      "name": "University of Virginia",
      "country": "USA",
      "qs_ranking": 244
    },
    {
      "name": "Western University",
      "country": "Canada",
      "qs_ranking": 246
    },
    {
      "name": "University of Sussex",
      "country": "UK",
      "qs_ranking": 246
    },
    {
      "name": "University of Notre Dame",
      "country": "USA",
      "qs_ranking": 248
    },
    {
      "name": "Taylor's University",
      "country": "Malaysia",
      "qs_ranking": 251
    },
    {
      "name": "Friedrich-Alexander University Erlangen-Nürnberg",
      "country": "Germany",
      "qs_ranking": 254
    },
    {
      "name": "TU Dresden",
      "country": "Germany",
      "qs_ranking": 256
    },
    {
      "name": "Heriot-Watt University Malaysia",
      "country": "Malaysia",
      "qs_ranking": 256
    },
    {
      "name": "Queensland University of Technology",
      "country": "Australia",
      "qs_ranking": 258
    },
    {
      "name": "Case Western Reserve University",
      "country": "USA",
      "qs_ranking": 259
    },
    {
      "name": "University of Canterbury",
      "country": "New Zealand",
      "qs_ranking": 261
    },
    {
      "name": "University of Waikato",
      "country": "New Zealand",
      "qs_ranking": 261
    },
    {
      "name": "Université Paris Cité",
      "country": "France",
      "qs_ranking": 261
    },
    {
      "name": "University of Aberdeen",
      "country": "UK",
      "qs_ranking": 264
    },
    {
      "name": "Deakin University",
      "country": "Australia",
      "qs_ranking": 266
    },
    {
      "name": "Griffith University",
      "country": "Australia",
      "qs_ranking": 270
    },
    {
      "name": "UCSI University",
      "country": "Malaysia",
      "qs_ranking": 271
    },
    {
      "name": "University of Galway",
      "country": "Ireland",
      "qs_ranking": 273
    },
    {
      "name": "TU Darmstadt",
      "country": "Germany",
      "qs_ranking": 273
    },
    {
      "name": "Sciences Po",
      "country": "France",
      "qs_ranking": 273
    },
    {
      "name": "Royal College of Surgeons in Ireland",
      "country": "Ireland",
      "qs_ranking": 273
    },
    {
      "name": "Heriot-Watt University",
      "country": "UK",
      "qs_ranking": 274
    },
    {
      "name": "Heriot-Watt University Dubai",
      "country": "UAE",
      "qs_ranking": 274
    },
    {
      "name": "University of Massachusetts Amherst",
      "country": "USA",
      "qs_ranking": 275
    },
    {
      "name": "University at Buffalo, SUNY",
      "country": "USA",
      "qs_ranking": 290
    },
    {
      "name": "United Arab Emirates University",
      "country": "UAE",
      "qs_ranking": 290
    },
    {
      "name": "Swinburne University of Technology Sarawak",
      "country": "Malaysia",
      "qs_ranking": 291
    },
    {
      "name": "University of Arizona",
      "country": "USA",
      "qs_ranking": 293
    },
    {
      "name": "HEC Paris",
      "country": "France",
      "qs_ranking": 296
    },
    {
      "name": "University of Surrey",
      "country": "UK",
      "qs_ranking": 296
    },
    {
      "name": "Simon Fraser University",
      "country": "Canada",
      "qs_ranking": 298
    },
    {
      "name": "University of Strathclyde",
      "country": "UK",
      "qs_ranking": 301
    },
    {
      "name": "University College Cork",
      "country": "Ireland",
      "qs_ranking": 303
    },
    {
      "name": "University of Cologne",
      "country": "Germany",
      "qs_ranking": 308
    },
    {
      "name": "North Carolina State University",
      "country": "USA",
      "qs_ranking": 311
    },
    {
      "name": "University of Stuttgart",
      "country": "Germany",
      "qs_ranking": 312
    },
    {
      "name": "Swansea University",
      "country": "UK",
      "qs_ranking": 312
    },
    {
      "name": "University of East Anglia",
      "country": "UK",
      "qs_ranking": 313
    },
    {
      "name": "University of Münster",
      "country": "Germany",
      "qs_ranking": 314
    },
    {
      "name": "University of Tasmania",
      "country": "Australia",
      "qs_ranking": 318
    },
    {
      "name": "University of Colorado Boulder",
      "country": "USA",
      "qs_ranking": 320
    },
    {
      "name": "University of Miami",
      "country": "USA",
      "qs_ranking": 324
    },
    {
      "name": "Rutgers University–New Brunswick",
      "country": "USA",
      "qs_ranking": 328
    },
    {
      "name": "Université Grenoble Alpes",
      "country": "France",
      "qs_ranking": 334
    },
    {
      "name": "University of Reading",
      "country": "UK",
      "qs_ranking": 335
    },
    {
      "name": "Ulm University",
      "country": "Germany",
      "qs_ranking": 339
    },
    {
      "name": "Tufts University",
      "country": "USA",
      "qs_ranking": 344
    },
    {
      "name": "American University of Sharjah",
      "country": "UAE",
      "qs_ranking": 347
    },
    {
      "name": "University of Leicester",
      "country": "UK",
      "qs_ranking": 348
    },
    {
      "name": "Indiana University Bloomington",
      "country": "USA",
      "qs_ranking": 355
    },
    {
      "name": "University of Victoria",
      "country": "Canada",
      "qs_ranking": 359
    },
    {
      "name": "Western Sydney University",
      "country": "Australia",
      "qs_ranking": 360
    },
    {
      "name": "Goethe University Frankfurt",
      "country": "Germany",
      "qs_ranking": 360
    },
    {
      "name": "University of Illinois at Chicago",
      "country": "USA",
      "qs_ranking": 365
    },
    {
      "name": "George Washington University",
      "country": "USA",
      "qs_ranking": 371
    },
    {
      "name": "Flinders University",
      "country": "Australia",
      "qs_ranking": 374
    },
    {
      "name": "Stony Brook University",
      "country": "USA",
      "qs_ranking": 379
    },
    {
      "name": "University of Cincinnati",
      "country": "USA",
      "qs_ranking": 380
    },
    {
      "name": "University of Saskatchewan",
      "country": "Canada",
      "qs_ranking": 387
    },
    {
      "name": "Lincoln University NZ",
      "country": "New Zealand",
      "qs_ranking": 387
    },
    {
      "name": "University of South Florida",
      "country": "USA",
      "qs_ranking": 388
    },
    {
      "name": "Virginia Tech",
      "country": "USA",
      "qs_ranking": 389
    },
    {
      "name": "Royal Holloway, University of London",
      "country": "UK",
      "qs_ranking": 391
    },
    {
      "name": "UC Santa Cruz",
      "country": "USA",
      "qs_ranking": 393
    },
    {
      "name": "Ruhr University Bochum",
      "country": "Germany",
      "qs_ranking": 396
    },
    {
      "name": "University of Strasbourg",
      "country": "France",
      "qs_ranking": 408
    },
    {
      "name": "Université de Lyon",
      "country": "France",
      "qs_ranking": 410
    },
    {
      "name": "Kiel University",
      "country": "Germany",
      "qs_ranking": 410
    },
    {
      "name": "Johannes Gutenberg University Mainz",
      "country": "Germany",
      "qs_ranking": 410
    },
    {
      "name": "University of Dundee",
      "country": "UK",
      "qs_ranking": 412
    },
    {
      "name": "University of Essex",
      "country": "UK",
      "qs_ranking": 412
    },
    {
      "name": "University of Mannheim",
      "country": "Germany",
      "qs_ranking": 412
    },
    {
      "name": "University of Würzburg",
      "country": "Germany",
      "qs_ranking": 412
    },
    {
      "name": "Auckland University of Technology",
      "country": "New Zealand",
      "qs_ranking": 412
    },
    {
      "name": "Yeshiva University",
      "country": "USA",
      "qs_ranking": 413
    },
    {
      "name": "James Cook University",
      "country": "Australia",
      "qs_ranking": 415
    },
    {
      "name": "National University of Ireland Galway",
      "country": "Ireland",
      "qs_ranking": 421
    },
    {
      "name": "University of Sharjah",
      "country": "UAE",
      "qs_ranking": 426
    },
    {
      "name": "Murdoch University Dubai",
      "country": "UAE",
      "qs_ranking": 436
    },
    {
      "name": "University of Missouri",
      "country": "USA",
      "qs_ranking": 437
    },
    {
      "name": "Singapore University of Technology and Design",
      "country": "Singapore",
      "qs_ranking": 440
    },
    {
      "name": "Colorado State University",
      "country": "USA",
      "qs_ranking": 442
    },
    {
      "name": "James Cook University Singapore",
      "country": "Singapore",
      "qs_ranking": 445
    },
    {
      "name": "Aston University",
      "country": "UK",
      "qs_ranking": 446
    },
    {
      "name": "Edith Cowan University",
      "country": "Australia",
      "qs_ranking": 446
    },
    {
      "name": "University of Montpellier",
      "country": "France",
      "qs_ranking": 448
    },
    {
      "name": "Université Laval",
      "country": "Canada",
      "qs_ranking": 451
    },
    {
      "name": "University of Guelph",
      "country": "Canada",
      "qs_ranking": 451
    },
    {
      "name": "Leipzig University",
      "country": "Germany",
      "qs_ranking": 451
    },
    {
      "name": "Brigham Young University",
      "country": "USA",
      "qs_ranking": 451
    },
    {
      "name": "University of Kansas",
      "country": "USA",
      "qs_ranking": 452
    },
    {
      "name": "University of Bordeaux",
      "country": "France",
      "qs_ranking": 461
    },
    {
      "name": "University of Canberra",
      "country": "Australia",
      "qs_ranking": 461
    },
    {
      "name": "Syracuse University",
      "country": "USA",
      "qs_ranking": 461
    },
    {
      "name": "University of Georgia",
      "country": "USA",
      "qs_ranking": 461
    },
    {
      "name": "Swinburne University of Technology",
      "country": "Australia",
      "qs_ranking": 462
    },
    {
      "name": "University at Buffalo (SUNY)",
      "country": "USA",
      "qs_ranking": 466
    },
    {
      "name": "Washington State University",
      "country": "USA",
      "qs_ranking": 466
    },
    {
      "name": "University of Konstanz",
      "country": "Germany",
      "qs_ranking": 467
    },
    {
      "name": "Iowa State University",
      "country": "USA",
      "qs_ranking": 470
    },
    {
      "name": "University of Kent",
      "country": "UK",
      "qs_ranking": 470
    },
    {
      "name": "Brandeis University",
      "country": "USA",
      "qs_ranking": 470
    },
    {
      "name": "University of Texas at Dallas",
      "country": "USA",
      "qs_ranking": 470
    },
    {
      "name": "University of Central Florida",
      "country": "USA",
      "qs_ranking": 477
    },
    {
      "name": "University of Tennessee Knoxville",
      "country": "USA",
      "qs_ranking": 481
    },
    {
      "name": "Aix-Marseille University",
      "country": "France",
      "qs_ranking": 481
    },
    {
      "name": "Dalhousie University",
      "country": "Canada",
      "qs_ranking": 486
    },
    {
      "name": "Concordia University",
      "country": "Canada",
      "qs_ranking": 487
    },
    {
      "name": "Murdoch University",
      "country": "Australia",
      "qs_ranking": 487
    },
    {
      "name": "University of Stirling",
      "country": "UK",
      "qs_ranking": 487
    },
    {
      "name": "University of Bremen",
      "country": "Germany",
      "qs_ranking": 487
    },
    {
      "name": "University of Hawaii at Manoa",
      "country": "USA",
      "qs_ranking": 488
    },
    {
      "name": "Boston College",
      "country": "USA",
      "qs_ranking": 488
    },
    {
      "name": "Rensselaer Polytechnic Institute",
      "country": "USA",
      "qs_ranking": 491
    },
    {
      "name": "Leibniz University Hannover",
      "country": "Germany",
      "qs_ranking": 491
    },
    {
      "name": "Université Toulouse III",
      "country": "France",
      "qs_ranking": 491
    },
    {
      "name": "CQUniversity Australia",
      "country": "Australia",
      "qs_ranking": 495
    },
    {
      "name": "UC Riverside",
      "country": "USA",
      "qs_ranking": 497
    },
    {
      "name": "EDHEC Business School",
      "country": "France",
      "qs_ranking": 501
    },
    {
      "name": "Colorado School of Mines",
      "country": "USA",
      "qs_ranking": 501
    },
    {
      "name": "University of South Carolina",
      "country": "USA",
      "qs_ranking": 501
    },
    {
      "name": "University of Delaware",
      "country": "USA",
      "qs_ranking": 506
    },
    {
      "name": "SOAS, University of London",
      "country": "UK",
      "qs_ranking": 508
    },
    {
      "name": "Oregon State University",
      "country": "USA",
      "qs_ranking": 511
    },
    {
      "name": "University of Iowa",
      "country": "USA",
      "qs_ranking": 511
    },
    {
      "name": "INTI International University",
      "country": "Malaysia",
      "qs_ranking": 516
    },
    {
      "name": "Brunel University London",
      "country": "UK",
      "qs_ranking": 521
    },
    {
      "name": "University of Houston",
      "country": "USA",
      "qs_ranking": 521
    },
    {
      "name": "Saarland University",
      "country": "Germany",
      "qs_ranking": 521
    },
    {
      "name": "Canadian University Dubai",
      "country": "UAE",
      "qs_ranking": 523
    },
    {
      "name": "Clemson University",
      "country": "USA",
      "qs_ranking": 525
    },
    {
      "name": "Friedrich Schiller University Jena",
      "country": "Germany",
      "qs_ranking": 526
    },
    {
      "name": "University of Bayreuth",
      "country": "Germany",
      "qs_ranking": 527
    },
    {
      "name": "Missouri University of Science and Technology",
      "country": "USA",
      "qs_ranking": 527
    },
    {
      "name": "University of Utah",
      "country": "USA",
      "qs_ranking": 531
    },
    {
      "name": "Victoria University",
      "country": "Australia",
      "qs_ranking": 543
    },
    {
      "name": "Singapore Management University",
      "country": "Singapore",
      "qs_ranking": 545
    },
    {
      "name": "Oxford Brookes University",
      "country": "UK",
      "qs_ranking": 561
    },
    {
      "name": "University of Nebraska-Lincoln",
      "country": "USA",
      "qs_ranking": 561
    },
    {
      "name": "American University",
      "country": "USA",
      "qs_ranking": 562
    },
    {
      "name": "Auburn University",
      "country": "USA",
      "qs_ranking": 562
    },
    {
      "name": "University of Portsmouth",
      "country": "UK",
      "qs_ranking": 563
    },
    {
      "name": "University of Connecticut",
      "country": "USA",
      "qs_ranking": 565
    },
    {
      "name": "Binghamton University",
      "country": "USA",
      "qs_ranking": 571
    },
    {
      "name": "Southern Cross University",
      "country": "Australia",
      "qs_ranking": 576
    },
    {
      "name": "De Montfort University",
      "country": "UK",
      "qs_ranking": 581
    },
    {
      "name": "Bangor University",
      "country": "UK",
      "qs_ranking": 581
    },
    {
      "name": "Keele University",
      "country": "UK",
      "qs_ranking": 581
    },
    {
      "name": "University of Tennessee",
      "country": "USA",
      "qs_ranking": 591
    },
    {
      "name": "Liverpool John Moores University",
      "country": "UK",
      "qs_ranking": 591
    },
    {
      "name": "University of Hull",
      "country": "UK",
      "qs_ranking": 591
    },
    {
      "name": "Florida International University",
      "country": "USA",
      "qs_ranking": 591
    },
    {
      "name": "York University",
      "country": "Canada",
      "qs_ranking": 601
    },
    {
      "name": "Bond University",
      "country": "Australia",
      "qs_ranking": 601
    },
    {
      "name": "Coventry University",
      "country": "UK",
      "qs_ranking": 601
    },
    {
      "name": "City, University of London",
      "country": "UK",
      "qs_ranking": 601
    },
    {
      "name": "University of Plymouth",
      "country": "UK",
      "qs_ranking": 601
    },
    {
      "name": "University of New England",
      "country": "Australia",
      "qs_ranking": 601
    },
    {
      "name": "Anglia Ruskin University",
      "country": "UK",
      "qs_ranking": 601
    },
    {
      "name": "Bournemouth University",
      "country": "UK",
      "qs_ranking": 601
    },
    {
      "name": "Illinois Institute of Technology",
      "country": "USA",
      "qs_ranking": 601
    },
    {
      "name": "Lehigh University",
      "country": "USA",
      "qs_ranking": 601
    },
    {
      "name": "Texas Tech University",
      "country": "USA",
      "qs_ranking": 601
    },
    {
      "name": "Tulane University",
      "country": "USA",
      "qs_ranking": 601
    },
    {
      "name": "University of Oregon",
      "country": "USA",
      "qs_ranking": 601
    },
    {
      "name": "Sunway University",
      "country": "Malaysia",
      "qs_ranking": 601
    },
    {
      "name": "Baylor University",
      "country": "USA",
      "qs_ranking": 601
    },
    {
      "name": "Southern Methodist University",
      "country": "USA",
      "qs_ranking": 601
    },
    {
      "name": "Asia Pacific University of Technology & Innovation",
      "country": "Malaysia",
      "qs_ranking": 611
    },
    {
      "name": "Charles Darwin University",
      "country": "Australia",
      "qs_ranking": 621
    },
    {
      "name": "American University in Dubai",
      "country": "UAE",
      "qs_ranking": 621
    },
    {
      "name": "Zayed University",
      "country": "UAE",
      "qs_ranking": 621
    },
    {
      "name": "University of Texas at Arlington",
      "country": "USA",
      "qs_ranking": 632
    },
    {
      "name": "University of Salford",
      "country": "UK",
      "qs_ranking": 651
    },
    {
      "name": "Goldsmiths, University of London",
      "country": "UK",
      "qs_ranking": 651
    },
    {
      "name": "Florida State University",
      "country": "USA",
      "qs_ranking": 651
    },
    {
      "name": "Drexel University",
      "country": "USA",
      "qs_ranking": 651
    },
    {
      "name": "Temple University",
      "country": "USA",
      "qs_ranking": 651
    },
    {
      "name": "Wake Forest University",
      "country": "USA",
      "qs_ranking": 651
    },
    {
      "name": "Toronto Metropolitan University",
      "country": "Canada",
      "qs_ranking": 651
    },
    {
      "name": "University of Lincoln",
      "country": "UK",
      "qs_ranking": 651
    },
    {
      "name": "University of Arkansas",
      "country": "USA",
      "qs_ranking": 651
    },
    {
      "name": "George Mason University",
      "country": "USA",
      "qs_ranking": 651
    },
    {
      "name": "University of Oklahoma",
      "country": "USA",
      "qs_ranking": 651
    },
    {
      "name": "International Islamic University Malaysia",
      "country": "Malaysia",
      "qs_ranking": 661
    },
    {
      "name": "University of Westminster",
      "country": "UK",
      "qs_ranking": 670
    },
    {
      "name": "Carleton University",
      "country": "Canada",
      "qs_ranking": 671
    },
    {
      "name": "College of William & Mary",
      "country": "USA",
      "qs_ranking": 671
    },
    {
      "name": "University of Manitoba",
      "country": "Canada",
      "qs_ranking": 671
    },
    {
      "name": "Charles Sturt University",
      "country": "Australia",
      "qs_ranking": 671
    },
    {
      "name": "University of Brighton",
      "country": "UK",
      "qs_ranking": 671
    },
    {
      "name": "Kingston University London",
      "country": "UK",
      "qs_ranking": 671
    },
    {
      "name": "San Diego State University",
      "country": "USA",
      "qs_ranking": 671
    },
    {
      "name": "University of New Mexico",
      "country": "USA",
      "qs_ranking": 671
    },
    {
      "name": "Worcester Polytechnic Institute",
      "country": "USA",
      "qs_ranking": 671
    },
    {
      "name": "Martin Luther University Halle-Wittenberg",
      "country": "Germany",
      "qs_ranking": 671
    },
    {
      "name": "Stevens Institute of Technology",
      "country": "USA",
      "qs_ranking": 691
    },
    {
      "name": "University of Greenwich",
      "country": "UK",
      "qs_ranking": 691
    },
    {
      "name": "Federation University Australia",
      "country": "Australia",
      "qs_ranking": 691
    },
    {
      "name": "Technological University Dublin",
      "country": "Ireland",
      "qs_ranking": 691
    },
    {
      "name": "University of Bradford",
      "country": "UK",
      "qs_ranking": 691
    },
    {
      "name": "Glasgow Caledonian University",
      "country": "UK",
      "qs_ranking": 691
    },
    {
      "name": "Justus Liebig University Giessen",
      "country": "Germany",
      "qs_ranking": 691
    },
    {
      "name": "Ulster University",
      "country": "UK",
      "qs_ranking": 691
    },
    {
      "name": "University of Huddersfield",
      "country": "UK",
      "qs_ranking": 691
    },
    {
      "name": "University of the West of England",
      "country": "UK",
      "qs_ranking": 691
    },
    {
      "name": "Oklahoma State University",
      "country": "USA",
      "qs_ranking": 691
    },
    {
      "name": "Saint Louis University",
      "country": "USA",
      "qs_ranking": 691
    },
    {
      "name": "Fordham University",
      "country": "USA",
      "qs_ranking": 701
    },
    {
      "name": "University of North Texas",
      "country": "USA",
      "qs_ranking": 701
    },
    {
      "name": "Kent State University",
      "country": "USA",
      "qs_ranking": 706
    },
    {
      "name": "Louisiana State University",
      "country": "USA",
      "qs_ranking": 706
    },
    {
      "name": "The New School",
      "country": "USA",
      "qs_ranking": 706
    },
    {
      "name": "Wayne State University",
      "country": "USA",
      "qs_ranking": 706
    },
    {
      "name": "Multimedia University",
      "country": "Malaysia",
      "qs_ranking": 711
    },
    {
      "name": "University of New Brunswick",
      "country": "Canada",
      "qs_ranking": 712
    },
    {
      "name": "Middlesex University Dubai",
      "country": "UAE",
      "qs_ranking": 721
    },
    {
      "name": "Acadia University",
      "country": "Canada",
      "qs_ranking": 751
    },
    {
      "name": "University of Maryland, Baltimore County",
      "country": "USA",
      "qs_ranking": 771
    },
    {
      "name": "University of Northern British Columbia",
      "country": "Canada",
      "qs_ranking": 781
    },
    {
      "name": "New Jersey Institute of Technology",
      "country": "USA",
      "qs_ranking": 791
    },
    {
      "name": "University of Kentucky",
      "country": "USA",
      "qs_ranking": 795
    },
    {
      "name": "University of Southern Queensland",
      "country": "Australia",
      "qs_ranking": 801
    },
    {
      "name": "Manchester Metropolitan University",
      "country": "UK",
      "qs_ranking": 801
    },
    {
      "name": "Middlesex University",
      "country": "UK",
      "qs_ranking": 801
    },
    {
      "name": "University of Central Lancashire",
      "country": "UK",
      "qs_ranking": 801
    },
    {
      "name": "Birkbeck, University of London",
      "country": "UK",
      "qs_ranking": 801
    },
    {
      "name": "Brock University",
      "country": "Canada",
      "qs_ranking": 801
    },
    {
      "name": "Memorial University of Newfoundland",
      "country": "Canada",
      "qs_ranking": 801
    },
    {
      "name": "University of Alabama",
      "country": "USA",
      "qs_ranking": 801
    },
    {
      "name": "University of Regina",
      "country": "Canada",
      "qs_ranking": 801
    },
    {
      "name": "University of Windsor",
      "country": "Canada",
      "qs_ranking": 801
    },
    {
      "name": "London South Bank University",
      "country": "UK",
      "qs_ranking": 801
    },
    {
      "name": "Philipps University of Marburg",
      "country": "Germany",
      "qs_ranking": 801
    },
    {
      "name": "University of Rostock",
      "country": "Germany",
      "qs_ranking": 801
    },
    {
      "name": "BITS Pilani Dubai Campus",
      "country": "UAE",
      "qs_ranking": 801
    },
    {
      "name": "Universiti Tunku Abdul Rahman",
      "country": "Malaysia",
      "qs_ranking": 801
    },
    {
      "name": "Abu Dhabi University",
      "country": "UAE",
      "qs_ranking": 801
    },
    {
      "name": "Middlesex University London",
      "country": "UK",
      "qs_ranking": 801
    },
    {
      "name": "DePaul University",
      "country": "USA",
      "qs_ranking": 801
    },
    {
      "name": "Florida Institute of Technology",
      "country": "USA",
      "qs_ranking": 801
    },
    {
      "name": "Loyola University Chicago",
      "country": "USA",
      "qs_ranking": 801
    },
    {
      "name": "Michigan Technological University",
      "country": "USA",
      "qs_ranking": 801
    },
    {
      "name": "University at Albany, SUNY",
      "country": "USA",
      "qs_ranking": 801
    },
    {
      "name": "University of Dayton",
      "country": "USA",
      "qs_ranking": 801
    },
    {
      "name": "University of New Hampshire",
      "country": "USA",
      "qs_ranking": 801
    },
    {
      "name": "University of Vermont",
      "country": "USA",
      "qs_ranking": 801
    },
    {
      "name": "University of Buckingham",
      "country": "UK",
      "qs_ranking": 851
    },
    {
      "name": "University of Hertfordshire",
      "country": "UK",
      "qs_ranking": 851
    },
    {
      "name": "Australian Catholic University",
      "country": "Australia",
      "qs_ranking": 851
    },
    {
      "name": "Maynooth University",
      "country": "Ireland",
      "qs_ranking": 851
    },
    {
      "name": "Robert Gordon University",
      "country": "UK",
      "qs_ranking": 851
    },
    {
      "name": "Aberystwyth University",
      "country": "UK",
      "qs_ranking": 851
    },
    {
      "name": "Birmingham City University",
      "country": "UK",
      "qs_ranking": 851
    },
    {
      "name": "Edinburgh Napier University",
      "country": "UK",
      "qs_ranking": 851
    },
    {
      "name": "University of Sunderland",
      "country": "UK",
      "qs_ranking": 851
    },
    {
      "name": "Kansas State University",
      "country": "USA",
      "qs_ranking": 851
    },
    {
      "name": "Mississippi State University",
      "country": "USA",
      "qs_ranking": 851
    },
    {
      "name": "Sheffield Hallam University",
      "country": "UK",
      "qs_ranking": 851
    },
    {
      "name": "University of Mississippi",
      "country": "USA",
      "qs_ranking": 851
    },
    {
      "name": "Heinrich Heine University Düsseldorf",
      "country": "Germany",
      "qs_ranking": 851
    },
    {
      "name": "University of Nantes",
      "country": "France",
      "qs_ranking": 851
    },
    {
      "name": "Université du Québec à Montréal",
      "country": "Canada",
      "qs_ranking": 851
    },
    {
      "name": "Miami University",
      "country": "USA",
      "qs_ranking": 851
    },
    {
      "name": "University of Massachusetts Lowell",
      "country": "USA",
      "qs_ranking": 851
    },
    {
      "name": "University of North Carolina at Charlotte",
      "country": "USA",
      "qs_ranking": 851
    },
    {
      "name": "West Virginia University",
      "country": "USA",
      "qs_ranking": 851
    },
    {
      "name": "University of East London",
      "country": "UK",
      "qs_ranking": 901
    },
    {
      "name": "Queen Margaret University",
      "country": "UK",
      "qs_ranking": 951
    },
    {
      "name": "University of Louisville",
      "country": "USA",
      "qs_ranking": 951
    },
    {
      "name": "University of Toledo",
      "country": "USA",
      "qs_ranking": 951
    },
    {
      "name": "University of Wisconsin-Milwaukee",
      "country": "USA",
      "qs_ranking": 951
    },
    {
      "name": "Torrens University Australia",
      "country": "Australia",
      "qs_ranking": 1001
    },
    {
      "name": "Staffordshire University",
      "country": "UK",
      "qs_ranking": 1001
    },
    {
      "name": "Rochester Institute of Technology",
      "country": "USA",
      "qs_ranking": 1001
    },
    {
      "name": "RIT Dubai",
      "country": "UAE",
      "qs_ranking": 1001
    },
    {
      "name": "London Metropolitan University",
      "country": "UK",
      "qs_ranking": 1001
    },
    {
      "name": "Bath Spa University",
      "country": "UK",
      "qs_ranking": 1001
    },
    {
      "name": "Canterbury Christ Church University",
      "country": "UK",
      "qs_ranking": 1001
    },
    {
      "name": "Howard University",
      "country": "USA",
      "qs_ranking": 1001
    },
    {
      "name": "Leeds Beckett University",
      "country": "UK",
      "qs_ranking": 1001
    },
    {
      "name": "Loyola Marymount University",
      "country": "USA",
      "qs_ranking": 1001
    },
    {
      "name": "University of Northampton",
      "country": "UK",
      "qs_ranking": 1001
    },
    {
      "name": "University of Texas at San Antonio",
      "country": "USA",
      "qs_ranking": 1001
    },
    {
      "name": "University of Wolverhampton",
      "country": "UK",
      "qs_ranking": 1001
    },
    {
      "name": "University of the Sunshine Coast",
      "country": "Australia",
      "qs_ranking": 1001
    },
    {
      "name": "University of Worcester",
      "country": "UK",
      "qs_ranking": 1001
    },
    {
      "name": "Arts University Bournemouth",
      "country": "UK",
      "qs_ranking": 1001
    },
    {
      "name": "University of West London",
      "country": "UK",
      "qs_ranking": 1001
    },
    {
      "name": "Northern Arizona University",
      "country": "USA",
      "qs_ranking": 1001
    },
    {
      "name": "Saint Peter's University",
      "country": "USA",
      "qs_ranking": 1001
    },
    {
      "name": "University of Massachusetts Boston",
      "country": "USA",
      "qs_ranking": 1001
    },
    {
      "name": "University of South Dakota",
      "country": "USA",
      "qs_ranking": 1001
    },
    {
      "name": "University of Tulsa",
      "country": "USA",
      "qs_ranking": 1001
    },
    {
      "name": "University of Derby",
      "country": "UK",
      "qs_ranking": 1201
    },
    {
      "name": "University of Roehampton",
      "country": "UK",
      "qs_ranking": 1201
    },
    {
      "name": "Marquette University",
      "country": "USA",
      "qs_ranking": 1201
    },
    {
      "name": "New Mexico State University",
      "country": "USA",
      "qs_ranking": 1201
    },
    {
      "name": "University of San Diego",
      "country": "USA",
      "qs_ranking": 1201
    },
    {
      "name": "Harper Adams University",
      "country": "UK",
      "qs_ranking": 1201
    },
    {
      "name": "Vancouver Island University",
      "country": "Canada",
      "qs_ranking": 1201
    },
    {
      "name": "Cleveland State University",
      "country": "USA",
      "qs_ranking": 1201
    },
    {
      "name": "Florida Atlantic University",
      "country": "USA",
      "qs_ranking": 1201
    },
    {
      "name": "San Francisco State University",
      "country": "USA",
      "qs_ranking": 1201
    },
    {
      "name": "University of Memphis",
      "country": "USA",
      "qs_ranking": 1201
    },
    {
      "name": "University of San Francisco",
      "country": "USA",
      "qs_ranking": 1201
    },
    {
      "name": "California State University, Long Beach",
      "country": "USA",
      "qs_ranking": 1401
    },
    {
      "name": "Teesside University",
      "country": "UK",
      "qs_ranking": 1401
    },
    {
      "name": "California Polytechnic State University",
      "country": "USA",
      "qs_ranking": 1401
    },
    {
      "name": "Chapman University",
      "country": "USA",
      "qs_ranking": 1501
    },
    {
      "name": "Abertay University",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "Adelphi University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Algoma University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Algonquin College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Athabasca University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Atlantic Technological University",
      "country": "Ireland",
      "qs_ranking": null
    },
    {
      "name": "Audencia Business School",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "Bishop's University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "BPP University",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "Bradley University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "British Columbia Institute of Technology (BCIT)",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Bucknell University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Burgundy School of Business",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "California State Polytechnic University, Pomona",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "California State University, East Bay",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "California State University, Fresno",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "California State University, Fullerton",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "California State University, Northridge",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "California State University, Sacramento",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Camosun College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Cape Breton University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Capilano University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Cardiff Metropolitan University",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "Centennial College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Centrale Lille",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "Centrale Nantes",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "Charité – Universitätsmedizin Berlin",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "Conestoga College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Durham College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Edge Hill University",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "EM Lyon Business School",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "EPF Engineering School",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "ESCE International Business School",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "ESCP Business School",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "ESMT Berlin",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "ESSEC Asia-Pacific Singapore",
      "country": "Singapore",
      "qs_ranking": null
    },
    {
      "name": "ESSEC Business School",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "Falmouth University",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "Fanshawe College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "FH Aachen",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "Florida Polytechnic University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Frankfurt School of Finance & Management",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "Georgian College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "GISMA University of Applied Sciences",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "Grenoble Ecole de Management",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "Hamburg University of Technology",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "Harvey Mudd College",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "HAW Hamburg",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "HELP University",
      "country": "Malaysia",
      "qs_ranking": null
    },
    {
      "name": "HHL Leipzig Graduate School of Management",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "Higher Colleges of Technology",
      "country": "UAE",
      "qs_ranking": null
    },
    {
      "name": "Hochschule Düsseldorf",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "Hochschule München",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "Hofstra University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Holland College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Holmes Institute",
      "country": "Australia",
      "qs_ranking": null
    },
    {
      "name": "HTW Berlin",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "Humber Polytechnic",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "IÉSEG School of Management",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "IMT Atlantique",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "James Madison University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "KEDGE Business School",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "Kwantlen Polytechnic University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Lakehead University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Lamar University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Langara College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Laurentian University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Lawrence Technological University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Leeds Trinity University",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "Lewis University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Liverpool Hope University",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "Long Island University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "MacEwan University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Manipal Academy of Higher Education Dubai",
      "country": "UAE",
      "qs_ranking": null
    },
    {
      "name": "Mohamed bin Zayed University of Artificial Intelligence",
      "country": "UAE",
      "qs_ranking": null
    },
    {
      "name": "Mohawk College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Mount Allison University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Mount Royal University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Munich Business School",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "Munster Technological University",
      "country": "Ireland",
      "qs_ranking": null
    },
    {
      "name": "New York Institute of Technology",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "New York University Abu Dhabi",
      "country": "UAE",
      "qs_ranking": null
    },
    {
      "name": "Niagara College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Northern Illinois University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "OCAD University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Pace University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Pepperdine University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Pomona College",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Pratt Institute",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Quinnipiac University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Regent's University London",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "Rennes School of Business",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "Rhode Island School of Design",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Royal Agricultural University",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "Royal College of Art",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "Royal Roads University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Royal Veterinary College",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "S P Jain School of Global Management Singapore",
      "country": "Singapore",
      "qs_ranking": null
    },
    {
      "name": "Saint Mary's University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Sam Houston State University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "San Jose State University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Santa Clara University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Savannah College of Art and Design",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "SEGi University",
      "country": "Malaysia",
      "qs_ranking": null
    },
    {
      "name": "Selkirk College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Seneca Polytechnic",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Sheridan College",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Singapore Institute of Technology",
      "country": "Singapore",
      "qs_ranking": null
    },
    {
      "name": "SKEMA Business School",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "Solent University",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "Southern Alberta Institute of Technology (SAIT)",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Southern Illinois University Edwardsville",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "St George's, University of London",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "St Mary's University, Twickenham",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "St. Francis Xavier University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Texas State University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Texas Woman's University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Thompson Rivers University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Toulouse School of Economics",
      "country": "France",
      "qs_ranking": null
    },
    {
      "name": "Trent University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Trinity Western University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "University of Adelaide College",
      "country": "Australia",
      "qs_ranking": null
    },
    {
      "name": "University of Akron",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "University of Augsburg",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "University of Bridgeport",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "University of Chester",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "University of Cumbria",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "University of Detroit Mercy",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "University of Divinity",
      "country": "Australia",
      "qs_ranking": null
    },
    {
      "name": "University of Gloucestershire",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "University of Greifswald",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "University of Hartford",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "University of Highlands and Islands",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "University of Houston-Clear Lake",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "University of Law",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "University of Lethbridge",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "University of New Haven",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "University of North Dakota",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "University of Potsdam",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "University of South Wales",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "University of Suffolk",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "University of Texas Rio Grande Valley",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "University of the Arts London",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "University of the Fraser Valley",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "University of the West of Scotland",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "University of Winchester",
      "country": "UK",
      "qs_ranking": null
    },
    {
      "name": "University of Winnipeg",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Western Illinois University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "WHU – Otto Beisheim School of Management",
      "country": "Germany",
      "qs_ranking": null
    },
    {
      "name": "Wichita State University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "Wilfrid Laurier University",
      "country": "Canada",
      "qs_ranking": null
    },
    {
      "name": "Wright State University",
      "country": "USA",
      "qs_ranking": null
    },
    {
      "name": "York St John University",
      "country": "UK",
      "qs_ranking": null
    }
  ]
} as const;
