import Link from "next/link";

export const metadata = {
  title: "Disclaimer — EduvianAI",
  description: "Important disclaimers about AI-generated recommendations, university data accuracy, and the scope of EduvianAI's services.",
};

/**
 * Public-facing Disclaimer page. Highlights the integrity boundaries of an
 * AI-driven recommendation platform separately from the longer Terms of Use,
 * so users do not have to read the full T&C to understand the limits of
 * what the platform's outputs mean.
 */
export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-white text-gray-900">
      <div className="max-w-3xl mx-auto px-6 py-12 prose prose-gray prose-sm sm:prose-base">
        <Link href="/" className="text-sm text-indigo-600 hover:text-indigo-800 no-underline">← Back to home</Link>

        <h1 className="mt-6 mb-2">Disclaimer</h1>
        <p className="text-sm text-gray-500 mt-0">Last updated: 1 May 2026</p>

        <p className="text-sm bg-amber-50 border border-amber-200 rounded p-3">
          EduvianAI is a decision-support tool. It is not a licensed educational consultant, immigration adviser, financial adviser, or legal adviser. The disclaimers below apply to every part of the platform.
        </p>

        <h2>1. AI-Generated Outputs Are Estimates</h2>
        <p>
          The recommendation engine, match scores, ROI projections, SOP drafts, LOR review, visa-prep guidance, and interview-prep feedback are generated by artificial intelligence (including third-party large language models). They are <b>educational suggestions and starting drafts, not professional advice</b>. They may contain inaccuracies, omissions, or biases. Always verify critical information through the official source before making any academic, financial, immigration, or legal decision.
        </p>

        <h2>2. University Data &mdash; Trust Levels</h2>
        <p>Each program is shown with one of two indicators:</p>
        <ul>
          <li>
            <span className="inline-block px-1.5 py-0.5 rounded bg-emerald-50 border border-emerald-200 text-emerald-700 text-xs font-bold">✓ Verified</span>
            &nbsp;: program data was extracted from the official university page on the date shown. <b>Even verified data may be outdated by the time you read it</b> &mdash; admission cycles roll over and universities change fees and deadlines without notice. Always reconfirm directly with the university before applying.
          </li>
          <li>
            <span className="inline-block px-1.5 py-0.5 rounded bg-amber-50 border border-amber-200 text-amber-700 text-xs font-bold">⚠ Listing only</span>
            &nbsp;: program data has not been re-verified against the official source for the current admissions cycle. Treat such entries as directional only.
          </li>
        </ul>
        <p>
          Where a fee or deadline is unavailable from the source page, the platform displays &ldquo;Verified fee not available &mdash; check University website&rdquo; rather than showing $0 or an estimate. We do not invent values we cannot verify.
        </p>

        <h2>3. Match Scores Are Not Predictions</h2>
        <p>
          The Safe / Reach / Ambitious tiers and the percentage match scores are computed from the profile inputs you provide. <b>They do not predict whether you will be admitted</b>. Universities make admission decisions through holistic review that considers factors we cannot model (essays, interviews, current cohort dynamics, internal quotas, year-on-year volatility).
        </p>

        <h2>4. Tool-Specific Limits</h2>
        <ul>
          <li><b>ROI Calculator / Parent Decision Tool</b>: outputs use median salary data and generic exchange-rate assumptions. They are illustrative only, not financial advice, and not a guarantee of post-graduation earnings.</li>
          <li><b>Visa Coach</b>: provides general guidance for educational purposes only. Not legal or immigration advice. Visa policies change frequently &mdash; always consult the official consular source and, where appropriate, a registered immigration adviser.</li>
          <li><b>SOP Assistant / LOR Coach</b>: produces draft text and feedback. <b>You are solely responsible for the truthfulness and authorship of any document you submit to a university</b>. Submitting AI-generated content as your own may violate the academic-integrity policies of universities and may result in admission revocation or rescission of any offer.</li>
          <li><b>Interview Prep / English-Test Lab</b>: practice and indicative feedback only. Not affiliated with the British Council, IDP, IELTS, ETS, Pearson PTE, or Duolingo. Does not predict your official test score.</li>
        </ul>

        <h2>5. No Guarantee of Outcome</h2>
        <p>
          EduvianAI does not guarantee admission, visa approval, scholarship awards, employment, or any post-study outcome. All such decisions are made at the sole discretion of the relevant institution or authority.
        </p>

        <h2>6. Third-Party Content</h2>
        <p>
          The platform contains links to university websites, scholarship boards, and government portals. We do not endorse, control, or take responsibility for the content, policies, or practices of those sites. Always verify on the official source.
        </p>

        <h2>7. Not a Substitute for Professional Advice</h2>
        <p>
          Information on this platform is not a substitute for consulting a qualified professional in your jurisdiction &mdash; an admissions counsellor, a registered immigration adviser, a financial planner, or an attorney &mdash; for advice tailored to your specific circumstances.
        </p>

        <p className="text-sm text-gray-600 mt-10">
          For the full legal framework, see our <Link href="/terms">Terms of Use</Link> and <Link href="/privacy">Privacy Policy</Link>.
        </p>
      </div>
    </main>
  );
}
